apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: twenty-crm
  namespace: cc-office
spec:
  parentRefs:
    - name: cc-office-web-gateway
  hostnames:
    - {{ .Values.domain.crm }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: twenty-crm
          port: 8000
