apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert
  namespace: cc-office
spec:
  secretName: authentik-secret
  issuerRef:
    name: cc-office-lets-encrypt
    kind: Issuer
  dnsNames:
    - {{ .Values.domain.auth }}
