# Main certificate issuer for Community Cloud
# This handles certifcate management for the default
# Gateway (cc-letsencrypt-web-gateway) used in the cluster
# and for office applications
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cc-lets-encrypt
  namespace: community-cloud
  labels:
    app.kubernetes.io/managed-by: "community-cloud"
spec:
  acme:
    email: {{ .Values.adminEmail }}
    profile: tlsserver
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cc-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            podTemplate:
              spec:
                nodeSelector:
                  node-role.kubernetes.io/worker: worker
